# nixpacks.toml (colocar na pasta /backend)
[phases.setup]
# Instala dependências do sistema necessárias para Pillow e outras libs (nomes corrigidos)
aptPkgs = ["libjpeg-dev", "zlib1g-dev", "libwebp-dev", "libtiff-dev", "liblcms2-dev", "libopenjp2-7-dev", "libfreetype6-dev", "tk-dev", "tcl-dev", "libharfbuzz-dev", "libfribidi-dev"]

[start]
# Comando para iniciar Gunicorn com worker Eventlet para suportar Socket.IO
cmd = "gunicorn --worker-class eventlet -w 1 src.main:app --bind 0.0.0.0:$PORT"
